Add and style contact section
izabelastanislawska/Montecinema pull request #9
Opened 2022-03-17 12:07 UTC by izabelastanislawska

2022-03-17 15:02 UTC, szymonlicau requested changes
I can see you've been busy tidying things up but it's starting to come along quite nicely! 🚀 
I've suggested a few things you could potentially refactor and also I'm not sure I understand one of your choices correctly - could you please elaborate on that one? 🙏

2022-03-18 10:16 UTC, izabelastanislawska commented on src/components/TheScreenings.vue
> +        </MovieCard> -->
It doesn't work :( I'm doing something wrong, that's why I commented it and I will be working on it later

2022-03-18 10:37 UTC, szymonlicau commented on src/components/TheScreenings.vue
> +        </MovieCard> -->
If you feel like you might need help with this - feel free to hit me up and we'll figure it out 😄

2022-03-21 10:50 UTC, izabelastanislawska commented on src/components/TheScreenings.vue
>      }
I fixed it, and also committed MovieCard fixes. Can you check?

2022-03-21 10:51 UTC, szymonlicau approved these changes

2022-03-21 10:59 UTC, merged